services:
  mysql:
    image: mysql:latest
    container_name: e-commerce_mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - application-network
    volumes:
      - ecommerce_mysql_volume:/var/lib/mysql

  springboot_backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: springboot_backend_container
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    networks:
      - application-network
    volumes:
      - "C:\\Users\\Ayush Gupta\\OneDrive\\Desktop\\Project\\ayush:/app"
      - "C:/Users/Ayush Gupta/.m2:/root/.m2"

networks:
  application-network:
    driver: bridge
volumes:
  ecommerce_mysql_volume: